version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    environment:
      POSTGRES_DB: marriage_booklet_development
      POSTGRES_USER: ${MARRIAGE_BOOKLET_DATABASE_USER}
      POSTGRES_PASSWORD: ${MARRIAGE_BOOKLET_DATABASE_PASSWORD}

