name: Verify
on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup System
        run: |
          sudo apt-get install libsqlite3-dev

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup

      - name: Run tests
        run: |
          bin/rails test
